// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.soja.repository;

import com.soja.repository.PersonaRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersonaRepository_Roo_Jpa_Repository {
    
    declare @type: PersonaRepository: @Transactional(readOnly = true);
    
}
